import Constants from "expo-constants";
import { Platform } from "react-native";
type RemoteMessage = { messageId?: string; data?: Record<string, string>; notification?: { title?: string; body?: string } };
type MessagingModule = { registerDeviceForRemoteMessages?: () => Promise<void>; getToken: () => Promise<string>; setBackgroundMessageHandler: (handler: (message: RemoteMessage) => Promise<void> | void) => void; onMessage: (listener: (message: RemoteMessage) => void) => () => void; onNotificationOpenedApp: (listener: (message: RemoteMessage) => void) => () => void; getInitialNotification: () => Promise<RemoteMessage | null>; onTokenRefresh: (listener: (token: string) => void) => () => void };
let messagingCache: Promise<MessagingModule | null> | null = null; let notificationsCache: Promise<any | null> | null = null; let configured = false; let backgroundRegistered = false;
function isExpoGo() { return (Constants as any).executionEnvironment === "storeClient" || (Constants as any).appOwnership === "expo"; }
async function notificationsModule() { if (isExpoGo()) return null; if (!notificationsCache) notificationsCache = import("expo-notifications").catch((e) => { console.warn("[JOD Notifications] expo-notifications unavailable", e); return null; }); return notificationsCache; }
async function messagingModule() { if (isExpoGo()) return null; if (!messagingCache) messagingCache = import("@react-native-firebase/messaging").then((m: any) => typeof m.default === "function" ? m.default() as MessagingModule : null).catch((e) => { console.warn("[JOD Notifications] Firebase messaging unavailable", e); return null; }); return messagingCache; }
function asRecord(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null ? value as Record<string, unknown> : null; }
export const notificationRuntimeService = {
  isExpoGo,
  async configure() { if (configured) return; const n = await notificationsModule(); if (!n) return; n.setNotificationHandler({ handleNotification: async () => ({ shouldShowAlert: true, shouldShowBanner: true, shouldShowList: true, shouldPlaySound: true, shouldSetBadge: true }) }); if (Platform.OS === "android" && n.setNotificationChannelAsync) await n.setNotificationChannelAsync("default", { name: "JOD", importance: 4, vibrationPattern: [0,250,250,250], sound: "default" }); configured = true; },
  async requestPermissions() { const n = await notificationsModule(); if (!n) return false; const current = await n.getPermissionsAsync(); if (current.granted) return true; return Boolean((await n.requestPermissionsAsync()).granted); },
  async getFcmToken() { const m = await messagingModule(); if (!m) return null; try { await m.registerDeviceForRemoteMessages?.(); const token = await m.getToken(); return token?.trim() || null; } catch (e) { console.warn("[JOD Notifications] getToken failed", e); return null; } },
  async showForeground(message: RemoteMessage) { const n = await notificationsModule(); if (!n) return; await n.scheduleNotificationAsync({ content: { title: message.notification?.title ?? message.data?.title ?? "إشعار جديد", body: message.notification?.body ?? message.data?.body ?? "", data: message.data ?? {}, sound: "default" }, trigger: null }); },
  extractResponseData(response: unknown) { const r = asRecord(response); const notification = asRecord(r?.notification); const request = asRecord(notification?.request); const content = asRecord(request?.content); const data = asRecord(content?.data); if (data) return data; const trigger = asRecord(request?.trigger); const remote = asRecord(trigger?.remoteMessage); return asRecord(remote?.data) ?? {}; },
  async setBadge(count: number) { const n = await notificationsModule(); if (n) await n.setBadgeCountAsync(Math.max(0, count)); },
  async registerBackground(handler: (message: RemoteMessage) => Promise<void> | void) { if (backgroundRegistered) return; const m = await messagingModule(); if (!m) return; m.setBackgroundMessageHandler(handler); backgroundRegistered = true; },
  async startListeners(listeners: { onForeground: (m: RemoteMessage) => void | Promise<void>; onOpened: (m: RemoteMessage | null) => void | Promise<void>; onResponse: (data: Record<string, unknown>) => void | Promise<void>; onTokenRefresh: (token: string) => void | Promise<void> }) { const stops: (() => void)[] = []; const n = await notificationsModule(); if (n) { const s = n.addNotificationResponseReceivedListener((r: unknown) => void listeners.onResponse(this.extractResponseData(r))); stops.push(() => s.remove()); } const m = await messagingModule(); if (m) { stops.push(m.onMessage((msg) => void listeners.onForeground(msg))); stops.push(m.onNotificationOpenedApp((msg) => void listeners.onOpened(msg))); stops.push(m.onTokenRefresh((token) => void listeners.onTokenRefresh(token))); try { const initial = await m.getInitialNotification(); if (initial) void listeners.onOpened(initial); } catch {} } return () => stops.forEach((s) => s()); },
};
export type MessagingRemoteMessage = RemoteMessage;
