import { useEffect } from "react";
import { useRouter } from "expo-router";
import { useQueryClient } from "@tanstack/react-query";
import { useAuthStatus } from "@/src/features/auth/queries";
import { notificationKeys } from "../query-keys";
import { notificationsApi } from "../api";
import { notificationTargetFromPayload } from "../navigation";
import { syncDeviceToken } from "../registration";
import { notificationRuntimeService } from "../services/notification-runtime.service";
export function useNotificationRuntimeSync() { const { isAuthenticated } = useAuthStatus(); const qc = useQueryClient(); const router = useRouter(); useEffect(() => { if (notificationRuntimeService.isExpoGo()) return; let active = true; let stop: (() => void) | null = null; const refresh = () => { void qc.invalidateQueries({ queryKey: notificationKeys.all }); }; const navigate = async (payload: Record<string, unknown> | null | undefined) => { const rawId = payload?.notificationId ?? payload?.notification_id; if (typeof rawId === "string" && rawId.trim() && isAuthenticated) { try { await notificationsApi.markRead(rawId.trim()); } catch {} } refresh(); const target = notificationTargetFromPayload(payload); if (target) router.push(target as never); }; const start = async () => { await notificationRuntimeService.configure(); const granted = await notificationRuntimeService.requestPermissions(); if (isAuthenticated && granted) { const token = await notificationRuntimeService.getFcmToken(); if (token) try { await syncDeviceToken(token); } catch (e) { console.warn("[JOD Notifications] device sync failed", e); } } await notificationRuntimeService.registerBackground(async () => {}); stop = await notificationRuntimeService.startListeners({ onForeground: async (message) => { if (isAuthenticated) { await notificationRuntimeService.showForeground(message); refresh(); } }, onOpened: async (message) => { await navigate(message?.data ?? null); }, onResponse: async (data) => { await navigate(data); }, onTokenRefresh: async (token) => { if (isAuthenticated) try { await syncDeviceToken(token); } catch (e) { console.warn("[JOD Notifications] token refresh sync failed", e); } } }); if (!active) stop?.(); }; void start(); return () => { active = false; stop?.(); }; }, [isAuthenticated, qc, router]); }
