import {
  CircleHelp,
  CircleUserRound,
  Bell,
  Bookmark,
  ChevronRight,
  Clock3,
  Search,
  Heart,
  Home,
  LogOut,
  Menu,
  MessageCircle,
  Megaphone,
  Newspaper,
  Clapperboard,
  Play,
  Info,
  Plus,
  Share2,
  Ellipsis,
  EllipsisVertical,
  GraduationCap,
  Settings,
  ShieldCheck,
  Sun,
  X,
  Moon,
  ChevronLeft,
  type LucideIcon,
} from "lucide-react-native";

export const appIcons = {
  notification: Bell,
  search: Search,
  menu: Menu,
  close: X,
  home: Home,
  profile: CircleUserRound,
  blogs: Newspaper,
  reels: Clapperboard,
  play: Play,
  createPost: Plus,
  myDonations: Heart,
  // Distinct from `help` (CircleHelp, used for the generic help-center "?"
  // icon) — CircleHelp's "?" mark sits inside the filled circle, so it
  // disappears when solid-filled for an active nav tab. Heart is a single
  // closed path, already used with `fill` on the post-card like button.
  helpOffers: Heart,
  savedPosts: Bookmark,
  comments: MessageCircle,
  shares: Share2,
  moreVertical: EllipsisVertical,
  more: Ellipsis,
  studentHub: GraduationCap,
  logout: LogOut,
  lightMode: Sun,
  darkMode: Moon,
  campaign: Megaphone,
  volunteer: Plus,
  clock: Clock3,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  settings: Settings,
  help: CircleHelp,
  shield: ShieldCheck,
  about: Info,
} satisfies Record<string, LucideIcon>;

export type AppIconKey = keyof typeof appIcons;
