import {
  CircleHelp,
  Bell,
  Bookmark,
  ChevronRight,
  Clock3,
  Search,
  Heart,
  Home,
  LogOut,
  Menu,
  MessageCircle,
  Megaphone,
  Newspaper,
  Info,
  Plus,
  Share2,
  EllipsisVertical,
  Settings,
  ShieldCheck,
  Sun,
  UserRound,
  X,
  Moon,
  ChevronLeft,
  type LucideIcon,
} from "lucide-react-native";

export const appIcons = {
  notification: Bell,
  search: Search,
  menu: Menu,
  close: X,
  home: Home,
  profile: UserRound,
  blogs: Newspaper,
  createPost: Plus,
  myDonations: Heart,
  savedPosts: Bookmark,
  comments: MessageCircle,
  shares: Share2,
  moreVertical: EllipsisVertical,
  logout: LogOut,
  lightMode: Sun,
  darkMode: Moon,
  campaign: Megaphone,
  volunteer: Plus,
  clock: Clock3,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  settings: Settings,
  help: CircleHelp,
  shield: ShieldCheck,
  about: Info,
} satisfies Record<string, LucideIcon>;

export type AppIconKey = keyof typeof appIcons;
