import * as ImagePicker from "expo-image-picker";
import { Image,Pressable,View } from "react-native";
import { ImagePlus,X } from "lucide-react-native";
import { useState } from "react";
import { ImageSourceDialog } from "@/src/components/shared/ImageSourceDialog";
import Text from "@/src/components/ui/Text";
import type { MediaUploadFile } from "@/src/features/media/types";
import { useToast } from "@/src/providers/ToastProvider";
export function PersonalCampaignImagesPicker({files,onChange}:{files:MediaUploadFile[];onChange:(files:MediaUploadFile[])=>void}){const toast=useToast();const[open,setOpen]=useState(false);const add=(asset:ImagePicker.ImagePickerAsset)=>{if(files.length>=10)return toast.error("يمكن إضافة 10 صور كحد أقصى.");if(asset.fileSize&&asset.fileSize>5*1024*1024)return toast.error("حجم الصورة يجب ألا يتجاوز 5MB.");onChange([...files,{uri:asset.uri,name:asset.fileName??`campaign-${Date.now()}.jpg`,type:asset.mimeType??"image/jpeg"}])};const gallery=async()=>{setOpen(false);const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(p.status!=="granted")return toast.error("اسمح للتطبيق بالوصول إلى الصور.");const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.85});if(!r.canceled&&r.assets[0])add(r.assets[0])};const camera=async()=>{setOpen(false);const p=await ImagePicker.requestCameraPermissionsAsync();if(p.status!=="granted")return toast.error("اسمح للتطبيق باستخدام الكاميرا.");const r=await ImagePicker.launchCameraAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.85});if(!r.canceled&&r.assets[0])add(r.assets[0])};return <><View className="gap-3"><View className="flex-row-reverse flex-wrap gap-2">{files.map((file,index)=><View key={`${file.uri}-${index}`} className="relative"><Image source={{uri:file.uri}} className="h-20 w-20 rounded-xl"/><Pressable onPress={()=>onChange(files.filter((_,i)=>i!==index))} className="absolute -left-1 -top-1 rounded-full bg-white p-1"><X size={13} color="#DC2626"/></Pressable></View>)}{files.length<10?<Pressable onPress={()=>setOpen(true)} className="h-20 w-20 items-center justify-center rounded-xl border border-dashed border-primary-400/50 bg-primary-400/5"><ImagePlus size={22} color="#4A9782"/></Pressable>:null}</View><Text size="2xs" className="text-gray-500 dark:text-gray-300">اختيار من المعرض أو التقاط صورة، بحد أقصى 10 صور.</Text></View><ImageSourceDialog visible={open} title="إضافة صورة للحملة" onClose={()=>setOpen(false)} onChooseGallery={()=>void gallery()} onTakePhoto={()=>void camera()}/></>}
